### ISSUE TITLE
Utilise template for more than one gallery

### ISSUE THREAD

**Issue by czescwojtek** [mjbp/storm-modal-gallery#1]
Hi Mick,

I was just wondering if it is fairly easy to utilise overlayInner template along with overlay element when initialising more than one gallery on a page. For instance, I am calling ModalGallery.init() twice, hoping to get two separate galleries (both being triggered by some link, so there's no option to see both of them at the same time). In result I get two modals. Would be cool if we just replace the contents of the first one.

Let me know if that makes sense.
Cheers,
Wojciech

**Comment by mjbp** [comment]
Hi Wojciech,

Sorry for the slow response and thanks for showing interest in the repo.

I agree that having duplicate gallery DOM is not the best. This was originally built for only one gallery per page - the idea was to collect all images in an article/post/page and create a gallery from them. The support for multiple galleries was added in haste at a later date for a specific project.

My first thoughts are that it may be better to create (and destroy) the DOM on open/close rather than have it persist and shared across gallery instances. I'm happy to make this update when I next find the time - hopefully this week.

Thanks again for taking the time to comment, I agree it's an improvement that should be made.

Cheers,
Mick
